### ISSUE TITLE
Pretrained weights are unavailable

### ISSUE THREAD

**Issue by caopulan** [SuhyeonHa/CDTNet-PyTorch#1]
Thanks for your job! Weights are canceled now, could you please share them again? Thanks a lot.

**Comment by SuhyeonHa** [comment]
Hello caopulan,

I'm so sorry, but the weight files are broken now.
I recommend you to refer to [SS3-High-Resolution-Image-Harmonization-via-Semantic-Spatial-Aware-3D-Lookup-Tables](https://github.com/SuhyeonHa/SS3-High-Resolution-Image-Harmonization-via-Semantic-Spatial-Aware-3D-Lookup-Tables) instead.
I'll update the files when I retrain the model.

Thanks.

**Comment by luoyuxuan0528** [comment]
is there Any Update about this issue?

**Comment by SuhyeonHa** [comment]
No plans for the time being, sorry.
